import base64
import requests
from antlr4 import *
from SiteLangListener import SiteLangListener

class SiteDeployListener(SiteLangListener):
    def __init__(self, github_token, vercel_token):
        self.github_token = github_token
        self.vercel_token = vercel_token
        self.site_name = ""
        self.site_attrs = {}
        self.pages = {}
        self._current_page = None

    def enterSite(self, ctx):
        self.site_name = ctx.STRING().getText().strip('"')

    def enterSiteAttr(self, ctx):
        key = ctx.IDENTIFIER().getText()
        val = ctx.expr().getText().strip('"')
        self.site_attrs[key] = val

    def enterPage(self, ctx):
        page_name = ctx.STRING().getText().strip('"')
        self._current_page = page_name
        self.pages[page_name] = {}

    def exitPage(self, ctx):
        self._current_page = None

    def enterPageAttr(self, ctx):
        if self._current_page is not None:
            key = ctx.IDENTIFIER().getText()
            val = ctx.expr().getText().strip('"')
            self.pages[self._current_page][key] = val

    def _generate_html(self):
        title = self.site_attrs.get("title", self.site_name)
        description = self.site_attrs.get("description", "")
        theme = self.site_attrs.get("theme", "light")

        bg = "#0f172a" if theme == "dark" else "#ffffff"
        fg = "#e2e8f0" if theme == "dark" else "#1e293b"
        card_bg = "#1e293b" if theme == "dark" else "#f8fafc"
        accent = "#4ade80"
        border = "#334155" if theme == "dark" else "#e2e8f0"

        index = self.pages.get("index", {})
        hero = index.get("hero", f"Welcome to {self.site_name}")
        about = index.get("about", "")
        contact = index.get("contact", "")

        about_section = f"""
  <section>
    <h2>About</h2>
    <p>{about}</p>
  </section>""" if about else ""

        contact_section = f"""
  <section>
    <h2>Contact</h2>
    <p><a href="mailto:{contact}">{contact}</a></p>
  </section>""" if contact else ""

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{title}</title>
  <meta name="description" content="{description}" />
  <style>
    *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{ font-family: 'Segoe UI', system-ui, sans-serif; background: {bg}; color: {fg}; line-height: 1.7; }}
    header {{ padding: 5rem 2rem 4rem; text-align: center; border-bottom: 1px solid {border}; }}
    header h1 {{ font-size: clamp(1.8rem, 5vw, 3rem); color: {accent}; margin-bottom: 0.75rem; }}
    header p {{ opacity: 0.7; font-size: 1.1rem; max-width: 600px; margin: 0 auto; }}
    main {{ max-width: 860px; margin: 0 auto; padding: 3rem 2rem; }}
    section {{ background: {card_bg}; border: 1px solid {border}; border-radius: 12px; padding: 2rem; margin-bottom: 1.5rem; }}
    section h2 {{ color: {accent}; font-size: 0.85rem; text-transform: uppercase; letter-spacing: 3px; margin-bottom: 0.75rem; }}
    section p {{ opacity: 0.85; }}
    a {{ color: {accent}; text-decoration: none; }}
    a:hover {{ text-decoration: underline; }}
    footer {{ text-align: center; padding: 2rem; opacity: 0.35; font-size: 0.8rem; border-top: 1px solid {border}; }}
    .badge {{ display: inline-block; background: {accent}22; color: {accent}; border: 1px solid {accent}44; border-radius: 999px; padding: 0.2rem 0.75rem; font-size: 0.75rem; margin-top: 1rem; }}
  </style>
</head>
<body>
  <header>
    <h1>{hero}</h1>
    <p>{description}</p>
    <span class="badge">Built with a custom DSL compiler</span>
  </header>
  <main>{about_section}{contact_section}
  </main>
  <footer>Universidad del Valle de Guatemala &mdash; Construcción de Compiladores 2026</footer>
</body>
</html>"""

    def _create_github_repo(self):
        repo_name = self.site_name.lower().replace(" ", "-").replace("_", "-")
        headers = {
            "Authorization": f"Bearer {self.github_token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28"
        }
        payload = {
            "name": repo_name,
            "description": self.site_attrs.get("description", "Generated by a custom DSL compiler"),
            "private": False,
            "auto_init": False
        }
        resp = requests.post("https://api.github.com/user/repos", headers=headers, json=payload)
        print("Status:", resp.status_code)
        print("Response:", resp.text)
        resp.raise_for_status()
        repo = resp.json()
        print(f"[+] GitHub repo created: {repo['html_url']}")
        return repo["full_name"], repo_name

    def _push_to_github(self, full_name, html_content):
        headers = {
            "Authorization": f"Bearer {self.github_token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28"
        }
        content_b64 = base64.b64encode(html_content.encode()).decode()
        resp = requests.put(
            f"https://api.github.com/repos/{full_name}/contents/index.html",
            headers=headers,
            json={"message": "Initial commit from compiler", "content": content_b64}
        )
        resp.raise_for_status()
        print(f"[+] index.html pushed to GitHub")

    def _deploy_to_vercel(self, repo_name, html_content):
        headers = {
            "Authorization": f"Bearer {self.vercel_token}",
            "Content-Type": "application/json"
        }
        payload = {
            "name": repo_name,
            "files": [{"file": "index.html", "data": html_content}],
            "projectSettings": {"framework": None},
            "target": "production"
        }
        resp = requests.post("https://api.vercel.com/v13/deployments", headers=headers, json=payload)
        resp.raise_for_status()
        data = resp.json()
        url = data.get("url") or (data.get("alias") or [None])[0]
        live_url = f"https://{url}" if url else "(check your Vercel dashboard)"
        print(f"[✓] Deployed to Vercel: {live_url}")
        return live_url

    def deploy(self):
        print(f"\n[*] Compiling site definition '{self.site_name}'...")
        html = self._generate_html()
        full_name, repo_name = self._create_github_repo()
        self._push_to_github(full_name, html)
        self._deploy_to_vercel(repo_name, html)
        print(f"\n[✓] Done! Your compiler just deployed a live website.")
